#!/bin/bash
#
# Copyright 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if test $# -ne 1
then
	echo "usage: $0 ARCH" 2>&1
	exit 1
fi
arch=$1

if test $arch != "full"
then
	find . -follow -name '*.[chCH]' -print | awk "\
		/\Documentation\// { next }
		/\/drivers\/s390\// { next }
		/\/include\/asm-generic\// { print }
		/\/include\/asm-$arch\// { print }
		/\/include\/asm-/ { next }
		/\/arch\/$arch\// { print }
		/\/arch\// { next }
		{ print }" > ctags.files
else
	find . -follow -name '*.[SschlyCGHL]' -print | fgrep -v "/drivers/s390/" > ctags.files
fi

ctags `cat ctags.files`
